### ISSUE TITLE
Docker container for istio-analytics fails to start

### ISSUE THREAD

**Issue by kimikowang** [istio-ecosystem/iter8#11]
/istio_analytics/startServerForDocker.sh: 17: /istio_analytics/startServerForDocker.sh: source: not found
Traceback (most recent call last):
  File "/istio_analytics/istio_analytics_restapi/app.py", line 7, in <module>
    from istio_analytics_restapi.api.restplus import api
  File "/istio_analytics/istio_analytics_restapi/api/restplus.py", line 11, in <module>
    format_checker=FormatChecker(formats=("date-time",)))
  File "/python3.6-venv/lib/python3.6/site-packages/jsonschema/_format.py", line 40, in __init__
    self.checkers = dict((k, self.checkers[k]) for k in formats)
  File "/python3.6-venv/lib/python3.6/site-packages/jsonschema/_format.py", line 40, in <genexpr>
    self.checkers = dict((k, self.checkers[k]) for k in formats)
KeyError: 'date-time'

**Comment by fabolive** [comment]
Fixed by commit 446216865e27ad325fbf1d2773a2ba030241eb83.
